// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJxoIb-KBUEeFMTj8CNyjhBNCd724YP8',
    appId: '1:172598483433:web:de755867249e970b265378',
    messagingSenderId: '172598483433',
    projectId: 'byte-academy-7ed75',
    authDomain: 'byte-academy-7ed75.firebaseapp.com',
    storageBucket: 'byte-academy-7ed75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrintuRMWgscsWrOzJbZTtUMp6FaYvFFg',
    appId: '1:172598483433:android:b837d7c3e04b50a0265378',
    messagingSenderId: '172598483433',
    projectId: 'byte-academy-7ed75',
    storageBucket: 'byte-academy-7ed75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ZsYp4BWnmUKeR-SyeVxrRk178H9vaBM',
    appId: '1:172598483433:ios:d77c40a8368c8708265378',
    messagingSenderId: '172598483433',
    projectId: 'byte-academy-7ed75',
    storageBucket: 'byte-academy-7ed75.appspot.com',
    iosBundleId: 'com.example.crystalacademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ZsYp4BWnmUKeR-SyeVxrRk178H9vaBM',
    appId: '1:172598483433:ios:f1b59376b4459fc5265378',
    messagingSenderId: '172598483433',
    projectId: 'byte-academy-7ed75',
    storageBucket: 'byte-academy-7ed75.appspot.com',
    iosBundleId: 'com.example.crystalacademy.RunnerTests',
  );
}
